services:
  - type: web
    name: stock-analysis-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend:app --bind 0.0.0.0:$PORT --workers 4
    envVars:
      - key: PORT
        value: 10000
      - key: TZ
        value: Asia/Kolkata
